### ISSUE TITLE
Message in statusbar phpstan(erred)

### ISSUE THREAD

**Issue by predragnikolic** [Rockstar04/SublimeLinter-contrib-phpstan#1]
First, thank you for making this :) 
but I have a problem of getting it to work

Sublime Linter v4.6.6
Sublime Linter Stan v0.2.0

Installed PhpStan globaly, and added the path `/home/predrag/.config/composer/vendor/bin` to Sublime linter `paths` settings.

I have a `do.php` file, with this content:
```php
<?php 

hello();
```  

I expect to show a errors count or error message in the panel. 
But nothing is shown except `phpstan(erred)` and when I open the panel it says `No lint results.

Enabled debuging in Sublime linter, and here is the log:

```
SublimeLinter: linter.py:887: Checking lint mode background vs lint reason on_load
SublimeLinter: #1 linter.py:907: 'phpstan' is linting 'do.php'
SublimeLinter: #1 util.py:142: PATH:
    /home/predrag/.config/composer/vendor/bin
    /home/predrag/.npm-global/bin
    /usr/local/sbin
    /usr/local/bin
    /usr/sbin
    /usr/bin
    /sbin
    /bin
    /usr/games
    /usr/local/games
SublimeLinter: #1 linter.py:1263: Running ...

  /home/predrag/Sites/forum  (working dir)
  $ /home/predrag/.config/composer/vendor/bin/phpstan analyse --errorFormat=raw --no-progress --autoload-file /home/predrag/Sites/forum/do.php --level max /home/predrag/Sites/forum/do.php

SublimeLinter: #1 linter.py:589: WARNING: phpstan output:
PHP Fatal error:  Uncaught Error: Call to undefined function hello() in /home/predrag/Sites/forum/do.php:3
Stack trace:
#0 phar:///home/predrag/.config/composer/vendor/phpstan/phpstan-shim/phpstan.phar/src/Command/AnalyseCommand.php(63): require_once()
#1 phar:///home/predrag/.config/composer/vendor/phpstan/phpstan-shim/phpstan.phar/vendor/symfony/console/Command/Command.php(241): PHPStan\Command\AnalyseCommand->execute(Object(PHPStanVendor\Symfony\Component\Console\Input\ArgvInput), Object(PHPStanVendor\Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///home/predrag/.config/composer/vendor/phpstan/phpstan-shim/phpstan.phar/vendor/symfony/console/Application.php(905): PHPStanVendor\Symfony\Component\Console\Command\Command->run(Object(PHPStanVendor\Symfony\Component\Console\Input\ArgvInput), Object(PHPStanVendor\Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///home/predrag/.config/composer/vendor/phpstan/phpstan-shim/phpstan.phar/vendor/symfony/console/Application.php(207): PHPStanVendor\Symfony\Component\C in /home/predrag/Sites/forum/do.php on line 3

SublimeLinter: #1 linter.py:591: Note: above warning will become an error in the future. Implement `on_stderr` if you think this is wrong.
SublimeLinter: sublime_linter.py:444: Linting buffer 25 took 0.23s

```

**Comment by Rockstar04** [comment]
After the past few SublimeLinter updates I noticed mine had broken as well, but havent had time to look into it. I will try to get a block of time set aside for looking into this sometime this week.

Thanks for taking the time to submit such a solid issue report, and thanks for trying out the plugin.
